### ISSUE TITLE
FileHeader not working

### ISSUE THREAD

**Issue by moffat** [shiyanhui/FileHeader#52]
Hi,

In the last few days, FileHeader stopped working. When I use the keyboard shortcut (I'm using ST2), the following shows up in the console:

using gpu buffer for window
Traceback (most recent call last):
  File "./sublime_plugin.py", line 337, in run_
  File "./FileHeader.py", line 565, in run
Boost.Python.ArgumentError: Python argument types in
    Window.show_input_panel(Window, str, NoneType, instancemethod, NoneType, NoneType)
did not match C++ signature:
    show_input_panel(SP<edit_window::reference>, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, boost::python::api::object, boost::python::api::object, boost::python::api::object)

Any ideas?

**Comment by moffat** [comment]
Also see in the console:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 185, in on_pre_save
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 184, in <lambda>
  File "./FileHeader.py", line 682, in on_pre_save
  File "./FileHeader.py", line 614, in update_automatically
ValueError: zero length field name in format
