### ISSUE TITLE
FileHeader is too slow

### ISSUE THREAD

**Issue by fate-lovely** [shiyanhui/FileHeader#77]
![file-header-slow](https://cloud.githubusercontent.com/assets/4210829/23391382/d56fb6aa-fdaf-11e6-8554-80fdb4e86055.gif)
It takes too much time to add header info.
OS: macOS Sierra
Memory: 16G
CPU: 2.2 GHz Intel Core i7 

Below is the console log.
```text
reloading settings Packages/FileHeader/FileHeader.sublime-settings
reloading plugin FileHeader.FileHeader
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 168, in reload_plugin
    el.on_activated(v)
  File "/Users/cj/Library/Application Support/Sublime Text 3/Packages/FileHeader/FileHeader.py", line 685, in on_activated
    block(view, self.update_automatically, view, FILE_PATH)
  File "/Users/cj/Library/Application Support/Sublime Text 3/Packages/FileHeader/FileHeader.py", line 339, in block
    _block()
  File "/Users/cj/Library/Application Support/Sublime Text 3/Packages/FileHeader/FileHeader.py", line 337, in _block
    callback(*args, **kwargs)
  File "/Users/cj/Library/Application Support/Sublime Text 3/Packages/FileHeader/FileHeader.py", line 594, in update_automatically
    syntax_type = get_syntax_type(view.file_name())
  File "/Users/cj/Library/Application Support/Sublime Text 3/Packages/FileHeader/FileHeader.py", line 298, in get_syntax_type
    if suffix in extension_equivalence:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by shiyanhui** [comment]
配置里边是不是把`extension_equivalence`去掉了？

**Comment by fate-lovely** [comment]
这是我的User配置。Default配置没有动。
```json
{
  "custom_template_header_path": "~/Dropbox/Mackup/Library/Application Support/Sublime Text 3/Packages/User/Header",
  "file_suffix_mapping": {
      "as": "ActionScript",
      "scpt": "AppleScript",
      "asp": "ASP",
      "aspx": "ASP",
      "bat": "Batch File",
      "cmd": "Batch File",
      "c": "C",
      "cs": "C#",
      "cpp": "C++",
      "clj": "Clojure",
      "css": "CSS",
      "styl": "CSS",
      "D": "D",
      "erl": "Erlang",
      "go": "Go",
      "groovy": "Groovy",
      "hs": "Haskell",
      "htm": "HTML",
      "html": "HTML",
      "java": "Java",
      "js": "JavaScript",
      "jsx": "JavaScript",
      "tex": "LaTeX",
      "lsp": "Lisp",
      "lua": "Lua",
      "md": "Markdown",
      "mat": "Matlab",
      "m": "Objective-C",
      "ml": "OCaml",
      "p": "Pascal",
      "pl": "Perl",
      "php": "PHP",
      "py": "Python",
      "R": "R",
      "rst": "RestructuredText",
      "rb": "Ruby",
      "scala": "Scala",
      "scss": "SCSS",
      "sh": "ShellScript",
      "sql": "SQL",
      "tcl": "TCL",
      "txt": "Text",
      "xml": "XML",
      "vue": "Vue"
  },
  "Default": {
    "email": "fatelovely1128@gmail.com",
    "author": "CJ Ting",
  },
}
```

**Comment by shiyanhui** [comment]
把default-settings拷贝到user-settings，然后修改你需要修改的地方就行了，其他的不要动。这个问题的原因，你把user-settings里边的extension_equivalence去掉了，导致调用sublime的api时找不到该设置。

**Comment by fate-lovely** [comment]
试了一下，变快了很多。建议可以改成说如果User配置没有的话，就使用默认配置。Python不熟，要么就PR了。
